### ISSUE TITLE
Eleventy 3.0.0 (>=alpha.15) causes tests to fail

### ISSUE THREAD

**Issue by noelforte** [noelforte/eleventy-plugin-vento#14]
Related to #13, can't merge until tests are able to pass. Source of regression has yet to be found, but for now this plugin only works with <= 3.0.0-alpha.14.

**Comment by paulrobertlloyd** [comment]
Experimenting with moving from Liquid to Vento via this plugin (with Eleventy 3.0.0-beta.1), and it seems that filters (added via `eleventyConfig.addFilter()`, but also tried using `eleventyConfig.addJavaScriptFunction()`) are not found.

Furthermore, following the example given for using JavaScript helper functions, I get the following error:

```
<p>This is something {{ italicize('really') }} important.</p>

> it.italicize is not a function
```

Does this relate to some of the issues being thrown up by these unit tests?

**Comment by noelforte** [comment]
@paulrobertlloyd Most likely, yes. I was working on an implementation to finalize the integration for filters and custom tags but life has kept me busy with other things the past month. My hope is to get back to this project in the next several weeks to address this issue which will ease the breaking changes that shipped with alpha.15 as well as fix #13.

Thanks for your patience!

**Comment by noelforte** [comment]
@paulrobertlloyd Following up on my comment from yesterday, and because I didn't state it verbatim, the workaround would be to hold eleventy at version `>=3.0.0-alpha.14` until I can get a release out that takes advantage of some 3.0.0 features and transitions away from what was removed (which is what's causing this plugin to break).

**Comment by noelforte** [comment]
@paulrobertlloyd Thanks for your patience on this, will ship in v3.0.0 which will bring full-featured support of paired shortcodes and shortcodes implemented as Vento tags. Exciting stuff!
