### ISSUE TITLE
v5.5.0 npm oackage is missing a `dist` folder

### ISSUE THREAD

**Issue by helenclx** [noelforte/eleventy-plugin-vento#603]
### Steps to reproduce

1. Install `eleventy-plugin-vento` or upgrade the plugin to v5.5.0.
2. Build an Eleventy site with `eleventy-plugin-vento` imported in Eleventy's configuration file (such as `eleventy.config.js`).

To reproduce the issue with a specific Eleventy project, you can try it with my developer website at https://github.com/helenclx/helenchong.dev, which is currently using v5.4.3 of `eleventy-plugin-vento`:
1. Clone the repository.
2. Run `npm install`.
3. Run `npm install eleventy-plugin-vento` to install the latest version (5.5.0) of the plugin.
4. Run `npm run build` to try to build my site.

### Expected behavior

Eleventy site built with no errors.

### Actual behavior

When I try to build my Eleventy site after upgrading `eleventy-plugin-vento to v5.5.0, or installing v5.5.0 of the plugin, Eleventy's CLI throws an error about import problem because it cannot find the `plugin.mjs` module of `eleventy-plugin-vento`:

```
[11ty] Eleventy Fatal Error (CLI):
[11ty] 1. Error in your Eleventy config file 'eleventy.config.js'. (via EleventyConfigError)
[11ty] 2. There was a problem importing 'eleventy.config.js' via import(esm) (via EleventyImportError)
[11ty] 3. Cannot find module '[Directory of my Eleventy project]/node_modules/eleventy-plugin-vento/dist/plugin.mjs' imported from [Directory of my Eleventy project]/eleventy.config.js
[11ty] 
[11ty] Original error stack trace: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '[Directory of my Eleventy project]/node_modules/eleventy-plugin-vento/dist/plugin.mjs' imported from [Directory of my Eleventy project]/eleventy.config.js
[11ty]     at finalizeResolution (node:internal/modules/esm/resolve:272:11)
[11ty]     at moduleResolve (node:internal/modules/esm/resolve:879:10)
[11ty]     at defaultResolve (node:internal/modules/esm/resolve:1006:11)
[11ty]     at #cachedDefaultResolve (node:internal/modules/esm/loader:704:20)
[11ty]     at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:724:38)
[11ty]     at nextStep (node:internal/modules/customization_hooks:189:26)
[11ty]     at resolve (file:///[Directory of my Eleventy project]/node_modules/@11ty/eleventy/src/Util/EsmResolver.js:54:9)
[11ty]     at nextStep (node:internal/modules/customization_hooks:189:26)
[11ty]     at resolveWithHooks (node:internal/modules/customization_hooks:417:10)
[11ty]     at ModuleLoader.resolveSync (node:internal/modules/esm/loader:750:16)
```

### Plugin version

5.5.0

### Eleventy version

3.1.6

### Additional information

OS; Arch Linux. Node.js version: 26.4.0. I have also compared the `eleventy-plugin-vento` npm package files of v5.5.0 and v5.4.3, and noticed that v5.4.3 has a `dist` folder, but v5.5.0 is missing a `dist` folder.

**Comment by noelforte** [comment]
Woah, weird...! Wonder how that happened...I'll deprecate and patch
